sudo: required

addons:
  sonarcloud:
    organization: mbegotner-github
    token:
      $SONAR_TOKEN

services:
  - docker

language: python

script:
  - python -m pytest -v
  - sonar-scanner

after_success:
  - sh .travis/deploy_dockerhub.sh
  - test "$TRAVIS_BRANCH" = "master" && .travis/deploy_heroku.sh
